# Generated by Django 5.2.15 on 2026-06-26 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('materials', 'Materials'), ('safety', 'Safety')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('static_image', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'FAQ items',
                'ordering': ['sort_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('industrial', 'Industrial'), ('commercial', 'Commercial'), ('repairs', 'Repairs'), ('residential', 'Residential')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('detail', models.CharField(max_length=120)),
                ('static_image', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('short', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('robot', 'Robot'), ('wrench', 'Wrench'), ('factory', 'Factory'), ('flame', 'Flame'), ('bolt', 'Bolt'), ('repair', 'Repair')], default='wrench', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KHODAK Metal Solution', max_length=120)),
                ('site_short', models.CharField(default='KHODAK', max_length=40)),
                ('site_tagline', models.CharField(default='Built for Durability. Engineered with Precision.', max_length=200)),
                ('site_description', models.TextField(default='Certified welding, metal structures, and fabrication for demanding industrial projects in Poole and across the UK.')),
                ('site_url', models.URLField(default='https://khodakmetal.co.uk')),
                ('site_phone', models.CharField(default='+44 1202 000 000', max_length=30)),
                ('site_email', models.EmailField(default='info@khodakmetal.co.uk', max_length=254)),
                ('site_address', models.CharField(default='Industrial Estate, Poole, Dorset BH15, UK', max_length=200)),
                ('site_year', models.PositiveIntegerField(default=2024)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='pages.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
