# Generated by Django 5.2.15 on 2026-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_update_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_address',
            field=models.CharField(default='564 Ashley Rd, Poole BH14 0AG, United Kingdom', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_email',
            field=models.EmailField(default='khodakmetalsolution@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_phone',
            field=models.CharField(default='+44 7704 039508', max_length=30),
        ),
    ]
