# Generated by Django 5.2.15 on 2026-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_update_site_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', 'title'], 'verbose_name': 'Стаття блогу', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['sort_order', 'question'], 'verbose_name': 'Питання FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Робота портфоліо', 'verbose_name_plural': 'Портфоліо'},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Налаштування сайту', 'verbose_name_plural': 'Налаштування сайту'},
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('closed', 'Закрита')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(default='https://khodakmetal.com'),
        ),
    ]
