# Generated by Django 5.2.15 on 2026-07-02 10:08

from django.db import migrations, models


def seed_site_blocks(apps, schema_editor):
    from pages.block_defaults import block_content_type, block_label, default_for_block
    from pages.site_content_registry import all_registry_block_keys

    SiteBlock = apps.get_model('pages', 'SiteBlock')
    for index, (page, key) in enumerate(all_registry_block_keys()):
        content_type = block_content_type(page, key)
        SiteBlock.objects.get_or_create(
            page=page,
            key=key,
            defaults={
                'label': block_label(page, key),
                'content_type': content_type,
                'text_html': default_for_block(page, key),
                'sort_order': index,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_merge_admin_labels_portfolio_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Hero',
                'verbose_name_plural': 'Про нас — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='AboutImperativesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Імперативи',
                'verbose_name_plural': 'Про нас — Імперативи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='AboutStorySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Історія',
                'verbose_name_plural': 'Про нас — Історія',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='BlogHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Блог — Hero',
                'verbose_name_plural': 'Блог — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='FaqHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ — Hero',
                'verbose_name_plural': 'FAQ — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeShowcaseSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Showcase',
                'verbose_name_plural': 'Головна — Showcase',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeValueGridSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Переваги',
                'verbose_name_plural': 'Головна — Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='PortfolioHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Портфоліо — Hero',
                'verbose_name_plural': 'Портфоліо — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='PrivacyPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ServicesCatalogSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Послуги — Каталог',
                'verbose_name_plural': 'Послуги — Каталог',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ServicesHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Послуги — Hero',
                'verbose_name_plural': 'Послуги — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ServicesSpecFormSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Послуги — Форма',
                'verbose_name_plural': 'Послуги — Форма',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='ServicesTimelineSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Послуги — Процес',
                'verbose_name_plural': 'Послуги — Процес',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал сайту',
                'verbose_name_plural': 'Підвал сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка сайту',
                'verbose_name_plural': 'Шапка сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteQuoteModalSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Модальне вікно заявки',
                'verbose_name_plural': 'Модальне вікно заявки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='TermsPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('services', 'Послуги'), ('portfolio', 'Портфоліо'), ('blog', 'Блог'), ('faq', 'FAQ'), ('contact', 'Контакти'), ('privacy', 'Privacy'), ('terms', 'Terms'), ('site', 'Сайт')], max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото')], default='text', max_length=16)),
                ('text_html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CMS блок',
                'verbose_name_plural': 'CMS блоки',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
        migrations.RunPython(seed_site_blocks, migrations.RunPython.noop),
    ]
