# Generated by Django 6.0.6 on 2026-07-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_update_ironwood_portfolio_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutherosettings',
            options={'verbose_name': 'Про нас — Верхній банер', 'verbose_name_plural': 'Про нас — Верхній банер'},
        ),
        migrations.AlterModelOptions(
            name='aboutimperativessettings',
            options={'verbose_name': 'Про нас — Цінності', 'verbose_name_plural': 'Про нас — Цінності'},
        ),
        migrations.AlterModelOptions(
            name='aboutstorysettings',
            options={'verbose_name': 'Про нас — Наша історія', 'verbose_name_plural': 'Про нас — Наша історія'},
        ),
        migrations.AlterModelOptions(
            name='blogherosettings',
            options={'verbose_name': 'Блог — Верхній банер', 'verbose_name_plural': 'Блог — Верхній банер'},
        ),
        migrations.AlterModelOptions(
            name='faqherosettings',
            options={'verbose_name': 'FAQ — Верхній банер', 'verbose_name_plural': 'FAQ — Верхній банер'},
        ),
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Головна — Верхній банер', 'verbose_name_plural': 'Головна — Верхній банер'},
        ),
        migrations.AlterModelOptions(
            name='homeshowcasesettings',
            options={'verbose_name': 'Головна — Проєкти', 'verbose_name_plural': 'Головна — Проєкти'},
        ),
        migrations.AlterModelOptions(
            name='portfolioherosettings',
            options={'verbose_name': 'Портфоліо — Верхній банер', 'verbose_name_plural': 'Портфоліо — Верхній банер'},
        ),
        migrations.AlterModelOptions(
            name='privacypagesettings',
            options={'verbose_name': 'Політика конфіденційності', 'verbose_name_plural': 'Політика конфіденційності'},
        ),
        migrations.AlterModelOptions(
            name='servicesherosettings',
            options={'verbose_name': 'Послуги — Верхній банер', 'verbose_name_plural': 'Послуги — Верхній банер'},
        ),
        migrations.AlterModelOptions(
            name='servicesspecformsettings',
            options={'verbose_name': 'Послуги — Форма специфікацій', 'verbose_name_plural': 'Послуги — Форма специфікацій'},
        ),
        migrations.AlterModelOptions(
            name='servicestimelinesettings',
            options={'verbose_name': 'Послуги — Як ми працюємо', 'verbose_name_plural': 'Послуги — Як ми працюємо'},
        ),
        migrations.AlterModelOptions(
            name='sitequotemodalsettings',
            options={'verbose_name': 'Вікно заявки', 'verbose_name_plural': 'Вікно заявки'},
        ),
        migrations.AlterModelOptions(
            name='termspagesettings',
            options={'verbose_name': 'Умови використання', 'verbose_name_plural': 'Умови використання'},
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата заявки'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='повідомлення'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='name',
            field=models.CharField(max_length=80, verbose_name="ім'я"),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='згода на обробку даних'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='pages.service', verbose_name='послуга'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('closed', 'Закрита')], default='new', max_length=20, verbose_name='статус'),
        ),
    ]
