# Generated by Django 5.2.15 on 2026-09-15 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_quoterequest_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='pages.portfolioitem')),
            ],
            options={
                'verbose_name': 'Фото портфоліо',
                'verbose_name_plural': 'Фото портфоліо',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
